apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "apirator.labels" . | nindent 4 }}
  name: {{ include "jaeger-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jaeger-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jaeger-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}