apiVersion: v1
kind: Service
metadata:
  name: {{ include "apirator.fullname" . }}
  labels:
    {{- include "apirator.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app.kubernetes.io/name: {{ include "apirator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
